# -*- coding: utf-8 -*-
"""
王者荣耀五级铭文库及 132 位英雄推荐铭文映射字典
"""

# 30 款五级铭文详细属性库
ARCANA_LEVEL_5_DICT = {
    "圣人": {"id": "1501", "name": "圣人", "color_type": "red", "color_name": "红色", "raw_des": "法术攻击力+5.3", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1501.png", "stats_1": {"magic_atk": 5.3}, "stats_10": {"magic_atk": 53.0}},
    "传承": {"id": "1503", "name": "传承", "color_type": "red", "color_name": "红色", "raw_des": "物理攻击力+3.2", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1503.png", "stats_1": {"phys_atk": 3.2}, "stats_10": {"phys_atk": 32.0}},
    "异变": {"id": "1504", "name": "异变", "color_type": "red", "color_name": "红色", "raw_des": "物理攻击力+2  物理穿透+3.6", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1504.png", "stats_1": {"phys_atk": 2.0, "phys_pierce": 3.6}, "stats_10": {"phys_atk": 20.0, "phys_pierce": 36.0}},
    "纷争": {"id": "1505", "name": "纷争", "color_type": "red", "color_name": "红色", "raw_des": "物理攻击力+2.5  物理吸血+0.5%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1505.png", "stats_1": {"phys_atk": 2.5, "phys_vamp_pct": 0.5}, "stats_10": {"phys_atk": 25.0, "phys_vamp_pct": 5.0}},
    "无双": {"id": "1510", "name": "无双", "color_type": "red", "color_name": "红色", "raw_des": "暴击率+0.7%  暴击效果+3.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1510.png", "stats_1": {"crit_rate_pct": 0.7, "crit_effect_pct": 3.6}, "stats_10": {"crit_rate_pct": 7.0, "crit_effect_pct": 36.0}},
    "宿命": {"id": "1512", "name": "宿命", "color_type": "red", "color_name": "红色", "raw_des": "攻速加成+1%  最大生命+33.7  物理防御力+2.3", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1512.png", "stats_1": {"atk_speed_pct": 1.0, "max_hp": 33.7, "phys_def": 2.3}, "stats_10": {"atk_speed_pct": 10.0, "max_hp": 337.0, "phys_def": 23.0}},
    "梦魇": {"id": "1514", "name": "梦魇", "color_type": "red", "color_name": "红色", "raw_des": "法术攻击力+4.2  法术穿透+2.4", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1514.png", "stats_1": {"magic_atk": 4.2, "magic_pierce": 2.4}, "stats_10": {"magic_atk": 42.0, "magic_pierce": 24.0}},
    "凶兆": {"id": "1517", "name": "凶兆", "color_type": "red", "color_name": "红色", "raw_des": "法术攻击力+4.2  攻速加成+0.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1517.png", "stats_1": {"magic_atk": 4.2, "atk_speed_pct": 0.6}, "stats_10": {"magic_atk": 42.0, "atk_speed_pct": 6.0}},
    "祸源": {"id": "1519", "name": "祸源", "color_type": "red", "color_name": "红色", "raw_des": "暴击率+1.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1519.png", "stats_1": {"crit_rate_pct": 1.6}, "stats_10": {"crit_rate_pct": 16.0}},
    "红月": {"id": "1520", "name": "红月", "color_type": "red", "color_name": "红色", "raw_des": "攻速加成+1.6%  暴击率+0.5%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/1520.png", "stats_1": {"atk_speed_pct": 1.6, "crit_rate_pct": 0.5}, "stats_10": {"atk_speed_pct": 16.0, "crit_rate_pct": 5.0}},
    "长生": {"id": "2501", "name": "长生", "color_type": "blue", "color_name": "蓝色", "raw_des": "最大生命+75", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2501.png", "stats_1": {"max_hp": 75.0}, "stats_10": {"max_hp": 750.0}},
    "贪婪": {"id": "2503", "name": "贪婪", "color_type": "blue", "color_name": "蓝色", "raw_des": "法术吸血+1.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2503.png", "stats_1": {"magic_vamp_pct": 1.6}, "stats_10": {"magic_vamp_pct": 16.0}},
    "夺萃": {"id": "2504", "name": "夺萃", "color_type": "blue", "color_name": "蓝色", "raw_des": "物理吸血+1.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2504.png", "stats_1": {"phys_vamp_pct": 1.6}, "stats_10": {"phys_vamp_pct": 16.0}},
    "兽痕": {"id": "2506", "name": "兽痕", "color_type": "blue", "color_name": "蓝色", "raw_des": "暴击率+0.5%  最大生命+60", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2506.png", "stats_1": {"crit_rate_pct": 0.5, "max_hp": 60.0}, "stats_10": {"crit_rate_pct": 5.0, "max_hp": 600.0}},
    "冥想": {"id": "2510", "name": "冥想", "color_type": "blue", "color_name": "蓝色", "raw_des": "最大生命+60  生命回复+4.5", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2510.png", "stats_1": {"max_hp": 60.0, "hp_regen": 4.5}, "stats_10": {"max_hp": 600.0, "hp_regen": 45.0}},
    "繁荣": {"id": "2511", "name": "繁荣", "color_type": "blue", "color_name": "蓝色", "raw_des": "物理吸血+1%  法术防御力+4.1", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2511.png", "stats_1": {"phys_vamp_pct": 1.0, "magic_def": 4.1}, "stats_10": {"phys_vamp_pct": 10.0, "magic_def": 41.0}},
    "轮回": {"id": "2512", "name": "轮回", "color_type": "blue", "color_name": "蓝色", "raw_des": "法术攻击力+2.4  法术吸血+1%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2512.png", "stats_1": {"magic_atk": 2.4, "magic_vamp_pct": 1.0}, "stats_10": {"magic_atk": 24.0, "magic_vamp_pct": 10.0}},
    "调和": {"id": "2515", "name": "调和", "color_type": "blue", "color_name": "蓝色", "raw_des": "最大生命+45  生命回复+5.2  移速+0.4%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2515.png", "stats_1": {"max_hp": 45.0, "hp_regen": 5.2, "move_speed_pct": 0.4}, "stats_10": {"max_hp": 450.0, "hp_regen": 52.0, "move_speed_pct": 4.0}},
    "隐匿": {"id": "2517", "name": "隐匿", "color_type": "blue", "color_name": "蓝色", "raw_des": "物理攻击力+1.6  移速+1%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2517.png", "stats_1": {"phys_atk": 1.6, "move_speed_pct": 1.0}, "stats_10": {"phys_atk": 16.0, "move_speed_pct": 10.0}},
    "狩猎": {"id": "2520", "name": "狩猎", "color_type": "blue", "color_name": "蓝色", "raw_des": "攻速加成+1%  移速+1%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/2520.png", "stats_1": {"atk_speed_pct": 1.0, "move_speed_pct": 1.0}, "stats_10": {"atk_speed_pct": 10.0, "move_speed_pct": 10.0}},
    "霸者": {"id": "3501", "name": "霸者", "color_type": "green", "color_name": "绿色", "raw_des": "物理防御力+9", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3501.png", "stats_1": {"phys_def": 9.0}, "stats_10": {"phys_def": 90.0}},
    "均衡": {"id": "3503", "name": "均衡", "color_type": "green", "color_name": "绿色", "raw_des": "物理防御力+5  法术防御力+5", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3503.png", "stats_1": {"phys_def": 5.0, "magic_def": 5.0}, "stats_10": {"phys_def": 50.0, "magic_def": 50.0}},
    "虚空": {"id": "3509", "name": "虚空", "color_type": "green", "color_name": "绿色", "raw_des": "最大生命+37.5  冷却缩减+0.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3509.png", "stats_1": {"max_hp": 37.5, "cd_reduction_pct": 0.6}, "stats_10": {"max_hp": 375.0, "cd_reduction_pct": 6.0}},
    "灵山": {"id": "3510", "name": "灵山", "color_type": "green", "color_name": "绿色", "raw_des": "法术防御力+9", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3510.png", "stats_1": {"magic_def": 9.0}, "stats_10": {"magic_def": 90.0}},
    "献祭": {"id": "3511", "name": "献祭", "color_type": "green", "color_name": "绿色", "raw_des": "法术攻击力+2.4  冷却缩减+0.7%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3511.png", "stats_1": {"magic_atk": 2.4, "cd_reduction_pct": 0.7}, "stats_10": {"magic_atk": 24.0, "cd_reduction_pct": 7.0}},
    "鹰眼": {"id": "3514", "name": "鹰眼", "color_type": "green", "color_name": "绿色", "raw_des": "物理攻击力+0.9  物理穿透+6.4", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3514.png", "stats_1": {"phys_atk": 0.9, "phys_pierce": 6.4}, "stats_10": {"phys_atk": 9.0, "phys_pierce": 64.0}},
    "心眼": {"id": "3515", "name": "心眼", "color_type": "green", "color_name": "绿色", "raw_des": "攻速加成+0.6%  法术穿透+6.4", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3515.png", "stats_1": {"atk_speed_pct": 0.6, "magic_pierce": 6.4}, "stats_10": {"atk_speed_pct": 6.0, "magic_pierce": 64.0}},
    "怜悯": {"id": "3516", "name": "怜悯", "color_type": "green", "color_name": "绿色", "raw_des": "冷却缩减+1%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3516.png", "stats_1": {"cd_reduction_pct": 1.0}, "stats_10": {"cd_reduction_pct": 10.0}},
    "敬畏": {"id": "3517", "name": "敬畏", "color_type": "green", "color_name": "绿色", "raw_des": "法术吸血+0.7%  物理防御力+5.9", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3517.png", "stats_1": {"magic_vamp_pct": 0.7, "phys_def": 5.9}, "stats_10": {"magic_vamp_pct": 7.0, "phys_def": 59.0}},
    "回声": {"id": "3518", "name": "回声", "color_type": "green", "color_name": "绿色", "raw_des": "物理防御力+2.7  法术防御力+2.7  冷却缩减+0.6%", "icon": "https://game.gtimg.cn/images/yxzj/img201606/mingwen/3518.png", "stats_1": {"phys_def": 2.7, "magic_def": 2.7, "cd_reduction_pct": 0.6}, "stats_10": {"phys_def": 27.0, "magic_def": 27.0, "cd_reduction_pct": 6.0}},
}

# 132 位国服英雄官方推荐铭文套组（红/绿/蓝各 10 颗满配）
HERO_RECOMMENDED_ARCANA = {
    "廉颇": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "小乔": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "赵云": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "墨子": {"red": "梦魇", "green": "怜悯", "blue": "狩猎"},
    "妲己": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "嬴政": {"red": "红月", "green": "心眼", "blue": "狩猎"},
    "孙尚香": {"red": "祸源", "green": "鹰眼", "blue": "隐匿"},
    "鲁班七号": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "庄周": {"red": "梦魇", "green": "心眼", "blue": "轮回"},
    "刘禅": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "高渐离": {"red": "梦魇", "green": "心眼", "blue": "贪婪"},
    "阿轲": {"red": "无双", "green": "鹰眼", "blue": "狩猎"},
    "钟无艳": {"red": "异变", "green": "鹰眼", "blue": "调和"},
    "孙膑": {"red": "梦魇", "green": "回声", "blue": "狩猎"},
    "扁鹊": {"red": "凶兆", "green": "心眼", "blue": "狩猎"},
    "孙悟空": {"red": "无双", "green": "鹰眼", "blue": "兽痕"},
    "心魔六耳": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "白起": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "芈月": {"red": "梦魇", "green": "怜悯", "blue": "狩猎"},
    "吕布": {"red": "红月", "green": "虚空", "blue": "隐匿"},
    "周瑜": {"red": "梦魇", "green": "献祭", "blue": "贪婪"},
    "夏侯惇": {"red": "宿命", "green": "鹰眼", "blue": "调和"},
    "甄姬": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "曹操": {"red": "宿命", "green": "鹰眼", "blue": "狩猎"},
    "典韦": {"red": "传承", "green": "虚空", "blue": "隐匿"},
    "宫本武藏": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "李白": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "马可波罗": {"red": "红月", "green": "鹰眼", "blue": "狩猎"},
    "狄仁杰": {"red": "纷争", "green": "鹰眼", "blue": "狩猎"},
    "达摩": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "项羽": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "武则天": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "老夫子": {"red": "红月", "green": "鹰眼", "blue": "狩猎"},
    "关羽": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "貂蝉": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "安琪拉": {"red": "圣人", "green": "献祭", "blue": "轮回"},
    "程咬金": {"red": "异变", "green": "均衡", "blue": "隐匿"},
    "露娜": {"red": "凶兆", "green": "心眼", "blue": "狩猎"},
    "姜子牙": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "刘邦": {"red": "宿命", "green": "虚空", "blue": "长生"},
    "韩信": {"red": "纷争", "green": "鹰眼", "blue": "兽痕"},
    "王昭君": {"red": "圣人", "green": "怜悯", "blue": "轮回"},
    "兰陵王": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "花木兰": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "张良": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "不知火舞": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "娜可露露": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "橘右京": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "亚瑟": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "牛魔": {"red": "宿命", "green": "均衡", "blue": "长生"},
    "后羿": {"red": "红月", "green": "鹰眼", "blue": "隐匿"},
    "刘备": {"red": "异变", "green": "鹰眼", "blue": "夺萃"},
    "张飞": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "李元芳": {"red": "红月", "green": "鹰眼", "blue": "隐匿"},
    "虞姬": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "钟馗": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "杨戬": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "雅典娜": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "蔡文姬": {"red": "圣人", "green": "均衡", "blue": "长生"},
    "太乙真人": {"red": "梦魇", "green": "献祭", "blue": "调和"},
    "哪吒": {"red": "宿命", "green": "虚空", "blue": "隐匿"},
    "诸葛亮": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "黄忠": {"red": "无双", "green": "鹰眼", "blue": "兽痕"},
    "大乔": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "东皇太一": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "干将莫邪": {"red": "梦魇", "green": "怜悯", "blue": "轮回"},
    "鬼谷子": {"red": "梦魇", "green": "献祭", "blue": "狩猎"},
    "铠": {"red": "传承", "green": "鹰眼", "blue": "隐匿"},
    "百里守约": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "百里玄策": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "苏烈": {"red": "异变", "green": "虚空", "blue": "隐匿"},
    "梦奇": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "女娲": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "明世隐": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "公孙离": {"red": "传承", "green": "鹰眼", "blue": "隐匿"},
    "杨玉环": {"red": "圣人", "green": "献祭", "blue": "轮回"},
    "裴擒虎": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "弈星": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "狂铁": {"red": "宿命", "green": "虚空", "blue": "狩猎"},
    "米莱狄": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "元歌": {"red": "祸源", "green": "鹰眼", "blue": "兽痕"},
    "孙策": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "司马懿": {"red": "凶兆", "green": "心眼", "blue": "贪婪"},
    "盾山": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "伽罗": {"red": "无双", "green": "鹰眼", "blue": "兽痕"},
    "沈梦溪": {"red": "梦魇", "green": "献祭", "blue": "轮回"},
    "李信": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "上官婉儿": {"red": "梦魇", "green": "心眼", "blue": "贪婪"},
    "嫦娥": {"red": "圣人", "green": "心眼", "blue": "调和"},
    "猪八戒": {"red": "异变", "green": "虚空", "blue": "调和"},
    "盘古": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "瑶": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "云中君": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "曜": {"red": "宿命", "green": "怜悯", "blue": "狩猎"},
    "马超": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "西施": {"red": "梦魇", "green": "心眼", "blue": "调和"},
    "鲁班大师": {"red": "梦魇", "green": "虚空", "blue": "调和"},
    "蒙犽": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "镜": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "蒙恬": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "阿古朵": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "夏洛特": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "澜": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "司空震": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "艾琳": {"red": "无双", "green": "心眼", "blue": "贪婪"},
    "云缨": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "金蝉": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "暃": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "桑启": {"red": "宿命", "green": "心眼", "blue": "调和"},
    "戈娅": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "海月": {"red": "梦魇", "green": "心眼", "blue": "调和"},
    "赵怀真": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "莱西奥": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "姬小满": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "亚连": {"red": "祸源", "green": "虚空", "blue": "狩猎"},
    "朵莉亚": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "海诺": {"red": "梦魇", "green": "心眼", "blue": "贪婪"},
    "敖隐": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "大司命": {"red": "异变", "green": "鹰眼", "blue": "狩猎"},
    "元流之子(法师)": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
    "元流之子(坦克)": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "少司缘": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "影": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "苍": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "空空儿": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "元流之子(射手)": {"red": "红月", "green": "鹰眼", "blue": "狩猎"},
    "孙权": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "蚩奼": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "元流之子(辅助)": {"red": "宿命", "green": "虚空", "blue": "调和"},
    "大禹": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "元流之子(刺客)": {"red": "异变", "green": "鹰眼", "blue": "隐匿"},
    "卢雅那": {"red": "祸源", "green": "鹰眼", "blue": "狩猎"},
    "王维": {"red": "梦魇", "green": "心眼", "blue": "狩猎"},
}
